[hardware]
  model = "ZNB"
  address = 'TCPIP0::192.168.1.218::inst0::INSTR'
  attenuation = 80
  port = "S43"

[sample]
  name = "ITRI"


[[measurement]]

  IF_bandwidth = 1000
  power = -20
  
  [measurement.frequency]
    deltafre = 10e6
    resonator_fre = 4.7612e9
    points = 501
