[hardware]
model = "E5080B"
address = "TCPIP0::192.168.1.78::inst0::INSTR"
attenuation = 110
port = "S43"

[sample]
name = "onecavity"

[[measurement]]
label = "C50490"
IF_bandwidth = 20
power = -44.0
repeat = 20
output = "C:\\Users\\ASUS\\Documents\\python training\\onecavity\\raw\\C50490\\att110_-44.0"

[measurement.frequency]
start = 5049006666
stop = 5049083023
points = 501

[[measurement]]
label = "C50490"
IF_bandwidth = 20
power = -43.0
repeat = 19
output = "C:\\Users\\ASUS\\Documents\\python training\\onecavity\\raw\\C50490\\att110_-43.0"

[measurement.frequency]
start = 5049006666
stop = 5049083023
points = 501

[[measurement]]
label = "C50490"
IF_bandwidth = 20
power = -42.0
repeat = 15
output = "C:\\Users\\ASUS\\Documents\\python training\\onecavity\\raw\\C50490\\att110_-42.0"

[measurement.frequency]
start = 5049006666
stop = 5049083023
points = 501

[[measurement]]
label = "C50490"
IF_bandwidth = 20
power = -41.0
repeat = 12
output = "C:\\Users\\ASUS\\Documents\\python training\\onecavity\\raw\\C50490\\att110_-41.0"

[measurement.frequency]
start = 5049006666
stop = 5049083023
points = 501
