

[hardware]
  model = "E5080B"
  address = "TCPIP0::192.168.1.78::inst0::INSTR"
  attenuation = 110
  port = "S43"

[sample]
  name = "onecavity"

[output]
  data_path = "C:\\Users\\ASUS\\Documents\\python training\\onecavity\\raw"

[[resonator]]
  label = "C50490"
  IF_bandwidth = 20
  [resonator.snr]
    max_repeat = 20
    min_repeat = 1
    power_ave_ratio = -140

  [resonator.power]
    min = -44
    max = -41
    step = 1
  [resonator.frequency]
    start = 5049006666
    stop = 5049083023
    points = 501
